In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])

result=np.where(arr1==5)
print(result)

(array([0, 2, 4, 6, 8]),)


In [8]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])

result=np.where(arr1%6)
print(result)

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [11]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])


result=np.searchsorted(arr1,8,side='left')
print(result)

7


In [12]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])


result=np.searchsorted(arr1,8,side='right')
print(result)

8


In [15]:
import numpy as np
arr1=np.array([[1,3,2],[5,4,6],[8,9,7]])


result=np.sort(arr1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
import numpy as np
a=np.array([1,2,3,4])


x=[False,True,True,False]
new=a[x]
print(x)
print(new)

[False, True, True, False]
[2 3]


In [21]:
import numpy as np
a=np.array([1,2,3,4])


x=[True,True,True,True]
new=a[x]
print(x)
print(new)

[True, True, True, True]
[1 2 3 4]
