In [1]:
import numpy as np 
a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [3]:
import numpy as np 
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [4]:
import numpy as np 
c = np.zeros((3,5))
print(c)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
d=np.random.random ((2,2))
print(d)


[[0.30713398 0.77173708]
 [0.61246791 0.68295859]]


In [6]:
e = np.arange(0,20,5)
print(e)

[ 0  5 10 15]


In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [8]:
flat=arr.flatten()
print(arr)
print(flat)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]
2
(3, 4)
int64


In [9]:
newtype=arr.astype('f')
print("\n convert array:\n",newtype)
print("\n converted array:\n",newtype)



 convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 converted array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]


In [10]:
size=len(arr)
print("\n siz of array:\n",size)


 siz of array:
 3
