In [3]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [5]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [6]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:3:2])
print(a[0::2])
print(a[1::])
print(a[2:,2:])
print(a[:,2])
print(a[:2:3])


[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12]]
[ 3  7 11]
[[1 2 3 4]]


In [8]:
rev_arr=arr[::-1]
print(rev_arr)


[9 8 7 6 5 4 3 2 1]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [2]:
reversed_array=arr[::-1]
print(reversed_array)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [3]:
col1=arr[:,0]
print(col1)


[1 4 7]


In [5]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [8]:
#array indexing in python
#single dimensional array

import numpy as np 
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])


10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [7]:
#multidimensional array 

import numpy as np 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])


1
6


In [12]:
#join functions

#horizontal join 

import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)#horizontal

#vertical join

result1=np.vstack((arr1,arr2))
print(result1)#vertical

#depth join 

result2=np.dstack((arr1,arr2))
print(result2)#depth


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [1]:
import numpy as np 
arr=np.array[(1,2,3,4,5,6)]
result=np.split(arr,3)
print(result)

arr1=np.array([1,2,3,4,5])
result1=np.array_split(arr1,3)
print(result1)

arr2=np.array([[1,2,3],[4,5,6]])
result2=np.hsplit(arr,3)
print(result2)

arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
result3=np.vsplit(arr,3)
print(result3)

result4=np.dsplit(arr3,2)
print(result4)



TypeError: 'builtin_function_or_method' object is not subscriptable